name = "skou-events"
main = "src/index.js"
compatibility_date = "2025-09-01"

# Bindings
[[d1_databases]]
binding = "DB"
database_name = "villiersdorp-events-db"
database_id = "823c5c97-9e4d-4305-93d1-1dfb2a6c3ac1"

[[kv_namespaces]]
binding = "EVENTS_KV"
id = "9ac093d84f2c499e97fff3bb17a386f1"

[[r2_buckets]]
binding = "TICKET_R2"
bucket_name = "villiersdorp-tickets"

[vars]
APP_NAME = "Villiersdorp Skou Tickets"
PHONE_NUMBER_ID = "780229961841826"
WHATSAPP_TOKEN = "EAFdiPX1jF1cBPfRwH05ag1wB8L4kEFQVNe85KDq0vY7dyhZCd2XZAZCwMffVnjXmJwDtklMHUPEBIM7ZBiupaT9PuORBYv3fBle3omsFKWmtwJuO2AvdsNH8lumV7ZAqW0KlagJl0sPZAthK2KVCR4JogcpTjzBByC3ZAWLK0jPr0awZCgPUU4JYtOA50k8ZC9ZAd7WAZDZD"
VERIFY_TOKEN = "vs-verify-2025"
PHONE_NUMBER_ID = "780229961841826"
BUSINESS_ID = "1266679118073583"
WHATSAPP_TEMPLATE_NAME = "vinetotp"
WHATSAPP_TEMPLATE_LANG = "af"
WHATSAPP_BUTTON_URL = "https://events.villiersdorpskou.co.za"
PUBLIC_BASE_URL = "https://tickets.villiersdorpskou.co.za"
QR_CDN = "https://api.qrserver.com/v1/create-qr-code/?size=512x512&data="

[observability.logs]
enabled = true

